export const ROUTES = {
  home: '/',
  sportskoKladjenje: 'sportsko-kladjenje',
  kladjenjeUzivo: 'kladjenje-uzivo',
  virtuelneIgre: 'virtuelne-igre',
  slotIgre: 'slot-igre',
  igreUzivo: 'igre-uzivo',
  brojevi: 'brojevi',
  promocije: 'promocije',
  blog: 'blog',
  balkanKlub: 'balkan-klub',
  register: 'register',
  sve: 'sve',
  triDana: '3-dana',
  uskoro: 'uskoro',
  pregled: 'pregled',
  pregledDesavanja: 'pregled-desavanja',
}
