export const ROUTES = {
    home: '/',
    sportskoKladjenje: 'sportsko-kladjenje',
    kladjenjeUzivo: 'kladjenje-uzivo',
    virtuelneIgre: 'virtuelne-igre',
    slotIgre: 'slot-igre',
    igreUzivo: 'igre-uzivo',
    brojevi: 'brojevi',
    promocije: 'promocije',
    blog: 'blog',
    balkanKlub: 'balkan-klub',
    register: 'register',
    sve: 'sve',
    triDana: '3-dana',
    danas: "danas",
    uskoro: "uskoro",
    ponedeljak: 'pon',
    utorak: 'uto',
    sreda: 'sre',
    cetvrtak: 'cet',
    petak: 'pet',
    subota: 'sub',
    nedelja: 'ned',
    pregled: 'pregled',
    pregledDesavanja: 'pregled-desavanja',
}